#!/bin/bash
protected_branch='master'
# current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
current_branch=$(git symbolic-ref --short HEAD)

if [[ $protected_branch == $current_branch ]]; then
  echo "Direct commits to the branch master are not allowed"
  exit 1
fi

# Run puppet syntaxcheck
# . $(git rev-parse --show-toplevel)/bin/syntaxcheck
