#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# Run Homebrew through the Brewfile
if [[ "$(uname -s)" == "Darwin" ]]; then
  echo "› brew bundle"
  brew bundle
fi

# find the installers and run them iteratively
find . -name install.sh -not -path "./_deprecated/*" | while read installer ; do sh -c "${installer}" ; done
